### ISSUE TITLE
[Errno 2] No such file or directory: 'whisper-ctranslate2'

### ISSUE THREAD

**Issue by levysantanna** [paulocoutinhox/py-transcriptor-ai#1]
MoviePy - Writing audio in temp/audio.mp3
MoviePy - Done.                                                                                                                                            
[SUCCESS] Audio extracted and saved to temp/audio.mp3
[l@fedora py-transcriptor-ai-main]$ python3 transcript-whisper.py
[DEBUG] Starting...
[DEBUG] Transcribing audio...
Traceback (most recent call last):
  File "/home/l/Downloads/py-transcriptor-ai-main/transcript-whisper.py", line 24, in <module>
    r.run(
  File "/home/l/.local/lib/python3.11/site-packages/pygemstones/system/runner.py", line 143, in run
    ret = subprocess.call(
          ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whisper-ctranslate2'
[l@fedora py-transcriptor-ai-main]$

**Comment by levysantanna** [comment]
I may forgot to install whisper library with python3 -m pip install whisper-ctranslate2

**Comment by paulocoutinhox** [comment]
Yes, it is on readme here:
https://github.com/paulocoutinhox/py-transcriptor-ai?tab=readme-ov-file#how-to-use-with-whisper

Thanks.
